blank_issues_enabled: false
contact_links:
  - name: ❓ Poser une question générale
    url: https://discord.gg/dq7Z52B
    about: Tu as une question ou veux suivre une spécialisation avec nos étudiants ? Viens sur Discord.
