name: Sync Markdown to Wiki v2

on:
  workflow_dispatch: # Permet un déclenchement manuel

jobs:
  sync_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo principal
        uses: actions/checkout@v3

      - name: Configure Git pour GitHub Actions
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone du Wiki avec Authentification
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Nettoyer complètement le Wiki (sauf .git)
        run: |
          cd wiki
          rm -rf *  # Supprime tous les fichiers existants sauf .git
          echo "Wiki vidé avant la synchronisation."

      - name: Copier tous les fichiers Markdown à la racine du Wiki
        run: |
          find . -name "*.md" -not -path "./wiki/*" -exec cp {} wiki/ \;

      - name: Définir README.md comme page d'accueil du Wiki
        run: |
          if [ -f wiki/README.md ]; then
            mv wiki/README.md wiki/Home.md
          fi

      - name: Générer une Table des Matières avec hiérarchie correcte
        run: |
          echo "## 📂 Table des Matières" > wiki/_Sidebar.md
          echo "" >> wiki/_Sidebar.md
          echo "- [🏠 Accueil](Home)" >> wiki/_Sidebar.md
          REPO_URL="https://github.com/${{ github.repository }}/wiki"

          generate_sidebar() {
            local current_path="$1"
            local indent_level="$2"

            for item in "$current_path"/*; do
              if [ -d "$item" ]; then
                folder_name=$(basename "$item" | sed 's/_/ /g')
                echo "$(printf '%*s' "$indent_level")- **${folder_name}**" >> wiki/_Sidebar.md
                generate_sidebar "$item" $((indent_level + 2)) # Récursion avec indentation
              elif [ -f "$item" ] && [[ "$item" == *.md ]]; then
                filename=$(basename "$item" .md)
                filename_readable=$(echo "$filename" | sed 's/_/ /g')
                echo "$(printf '%*s' "$indent_level")  - [${filename_readable}](${REPO_URL}/${filename})" >> wiki/_Sidebar.md
              fi
            done
          }

          generate_sidebar "." 0

      - name: Commit et push des fichiers mis à jour
        run: |
          cd wiki
          git add .
          git commit -m "Mise à jour automatique du Wiki avec hiérarchie correcte" || echo "Aucune modification détectée"
          git push
