name: Sync Markdown to Wiki v2

on:
  workflow_dispatch: # Permet uniquement un déclenchement manuel

jobs:
  sync_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo principal
        uses: actions/checkout@v3

      - name: Configure Git pour GitHub Actions
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone du Wiki avec Authentification
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Nettoyer complètement le Wiki (sauf .git)
        run: |
          cd wiki
          rm -rf *  # Supprime tous les fichiers existants sauf .git
          echo "Wiki vidé avant la synchronisation."

      - name: Copier tous les fichiers Markdown à la racine du Wiki
        run: |
          find . -name "*.md" -not -path "./wiki/*" -exec cp {} wiki/ \;

      - name: Définir README.md comme page d'accueil du Wiki
        run: |
          if [ -f wiki/README.md ]; then
            mv wiki/README.md wiki/Home.md
          fi

      - name: Générer une Table des Matières avec hiérarchie corrigée
        run: |
          echo "## 📂 Table des Matières" > wiki/_Sidebar.md
          echo "" >> wiki/_Sidebar.md
          echo "- [🏠 Accueil](Home)" >> wiki/_Sidebar.md
          REPO_URL="https://github.com/${{ github.repository }}/wiki"

          find . -type d -not -path "./wiki*" -not -path "./.git*" -not -path "./.github*" | sort | while read dir; do
              folder_name=$(basename "$dir" | sed 's/_/ /g') # Remplace les _ par espaces
              echo "<details>" >> wiki/_Sidebar.md
              echo "  <summary><b>${folder_name}</b></summary>" >> wiki/_Sidebar.md
              echo "  <ul>" >> wiki/_Sidebar.md

              find "$dir" -maxdepth 1 -type f -name "*.md" | sort | while read file; do
                  filename=$(basename "$file" .md)
                  filename_readable=$(echo "$filename" | sed 's/_/ /g') # Remplace les _ par espaces
                  echo "    <li><a href='${REPO_URL}/${filename}'>${filename_readable}</a></li>" >> wiki/_Sidebar.md
              done

              find "$dir" -mindepth 1 -type d | sort | while read subdir; do
                  subfolder_name=$(basename "$subdir" | sed 's/_/ /g')
                  echo "    <details>" >> wiki/_Sidebar.md
                  echo "      <summary><b>${subfolder_name}</b></summary>" >> wiki/_Sidebar.md
                  echo "      <ul>" >> wiki/_Sidebar.md

                  find "$subdir" -maxdepth 1 -type f -name "*.md" | sort | while read subfile; do
                      subfilename=$(basename "$subfile" .md)
                      subfilename_readable=$(echo "$subfilename" | sed 's/_/ /g') # Remplace les _ par espaces
                      echo "        <li><a href='${REPO_URL}/${subfilename}'>${subfilename_readable}</a></li>" >> wiki/_Sidebar.md
                  done

                  echo "      </ul>" >> wiki/_Sidebar.md
                  echo "    </details>" >> wiki/_Sidebar.md
              done

              echo "  </ul>" >> wiki/_Sidebar.md
              echo "</details>" >> wiki/_Sidebar.md
          done

      - name: Commit et push des fichiers mis à jour
        run: |
          cd wiki
          git add .
          git commit -m "Mise à jour automatique du Wiki avec hiérarchie corrigée" || echo "Aucune modification détectée"
          git push
