name: Sync Markdown to Wiki

on:
  push:
    branches:
      - master  # Exécute l'action à chaque push sur la branche principale
  workflow_dispatch: # Permet un déclenchement manuel

jobs:
  sync_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo principal
        uses: actions/checkout@v3

      - name: Configure Git pour GitHub Actions
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone du Wiki avec Authentification
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Nettoyer complètement le Wiki (sauf .git)
        run: |
          cd wiki
          rm -rf *  # Supprime tous les fichiers et dossiers
          rm -rf .github  # Supprime aussi les fichiers de configuration si présents
          echo "Wiki vidé avant la synchronisation."

      - name: Copier tous les fichiers Markdown en conservant la structure
        run: |
          rsync -av --prune-empty-dirs --include '*/' --include='*.md' --exclude='*' ./ wiki/

      - name: Définir README.md comme page d'accueil du Wiki
        run: |
          if [ -f wiki/README.md ]; then
            mv wiki/README.md wiki/Home.md
          fi

      - name: Générer un Index/Table des matières pour structurer les menus
        run: |
          echo "# Table des Matières" > wiki/_Sidebar.md
          echo "" >> wiki/_Sidebar.md
          
          # Ajouter un lien vers la page d'accueil
          echo "- [Accueil](Home)" >> wiki/_Sidebar.md
          
          # Parcourir les dossiers et ajouter une structure de menu
          for dir in $(find wiki/ -type d -mindepth 1 -not -path "wiki/.git*" -not -path "wiki/.github*"); do
            folder_name=$(basename "$dir")
            echo "- **$folder_name**" >> wiki/_Sidebar.md
            for file in "$dir"/*.md; do
              if [ -f "$file" ]; then
                filename=$(basename "$file" .md)
                echo "  - [$filename]($folder_name/$filename)" >> wiki/_Sidebar.md
              fi
            done
          done

      - name: Commit et push des fichiers mis à jour
        run: |
          cd wiki
          git add .
          git commit -m "Mise à jour automatique du Wiki après nettoyage" || echo "Aucune modification détectée"
          git push