name: Sync Markdown to Wiki

on:
  push:
    branches:
      - master  # Exécute l'action à chaque push sur la branche principale
  workflow_dispatch: # Permet un déclenchement manuel

jobs:
  sync_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo principal
        uses: actions/checkout@v3

      - name: Configure Git pour GitHub Actions
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone du Wiki avec Authentification
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Copier tous les fichiers Markdown (y compris les sous-dossiers)
        run: |
          find . -name "*.md" -not -path "./wiki/*" -exec cp --parents {} wiki/ \;
          rm -rf wiki/.github # Supprime les fichiers inutiles s'ils existent

      - name: Définir README.md comme page d'accueil du Wiki
        run: |
          if [ -f wiki/README.md ]; then
            mv wiki/README.md wiki/Home.md
          fi

      - name: Commit et push des fichiers mis à jour
        run: |
          cd wiki
          git add .
          git commit -m "Mise à jour automatique du Wiki" || echo "Aucune modification détectée"
          git push
